### ISSUE TITLE
[Mozilla FireFox] createBenchmarkrAccount error: Unparseable date: "01 Jan 1990"

### ISSUE THREAD

**Issue by OhadR** [OhadR/cft-calc--gae#53]
![image](https://cloud.githubusercontent.com/assets/2394980/4782009/a155b156-5cd2-11e4-9a13-90c3ddd17313.png)

/createBenchmarkrAccount
java.text.ParseException: Unparseable date: "01 Jan 1990"
	at java.text.DateFormat.parse(DateFormat.java:357)
	at com.ohadr.cbenchmarkr.web.WebController.createBenchmarkrAccount(WebController.java:270)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

when it works, it looks like:
[s~cbenchmarkr/3.377760749495134458].<stdout>: 06 Aug 2014 13:40:22,763 [Request D8DEB5A8] INFO  ohadr.cbenchmarkr.Manager:createBenchmarkrAccount:130 - traineeId: moshe@mosh3, isMale? true, DOB=Mon Jan 01 00:00:00 UTC 1990

but in this case: "01 Jan 1990"

*the request:*
2014-08-06 15:53:33.478 /createBenchmarkrAccount 500 66ms 0kb **Mozilla/5.0** (**iPhone**; CPU **iPhone OS 7_1_2** like Mac OS X) AppleWebKit/537.51.2 (KHTML, like Gecko) Mobile/11D257 [FBAN/FBIOS;FBAV/13.0.0.25.19;FBBV/3507499;FBDV/iPhone6,2;FBMD/iPhone;FBSN/iPhone OS;FBSV/7.1.2;FBSS/2; FBCR/O2;FBID/phone;FBLC/en_GB;FBOP/5] module=default version=3
86.6.51.53 - - [06/Aug/2014:05:53:33 -0700] "POST /createBenchmarkrAccount HTTP/1.1" 500 0 "http://cbenchmarkr.appspot.com/" "Mozilla/5.0 (iPhone; CPU iPhone OS 7_1_2 like Mac OS X) AppleWebKit/537.51.2 (KHTML, like Gecko) Mobile/11D257 [FBAN/FBIOS;FBAV/13.0.0.25.19;FBBV/3507499;FBDV/iPhone6,2;FBMD/iPhone;FBSN/iPhone OS;FBSV/7.1.2;FBSS/2; FBCR/O2;FBID/phone;FBLC/en_GB;FBOP/5]" "cbenchmarkr.appspot.com" ms=66 cpu_ms=21 app_engine_release=1.9.8 trace_id=7b172888c63bc66cb062dca0f1ad96df instance=00c61b117c776596d703cf55e7307f938b6361f8

**Comment by OhadR** [comment]
marked as "invalid" as i do not have create account form anymore - login with Facebook!
